// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TamlVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "TamlVS.7b83d024-c84a-4a22-8898-26756a60c934";
        public const string Name = "TamlVS";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0.902";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
