// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TamlVS
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorFactoryString = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string TamlVSString = "116eef20-e244-4800-a72a-77c14915b8cd";
        public static Guid TamlVS = new Guid(TamlVSString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TamlMenuGroup = 0x0001;
        public const int TamlMenu = 0x0002;
        public const int ConvertGroup = 0x0010;
        public const int SettingsGroup = 0x0020;
        public const int SortKeys = 0x0090;
        public const int CopyAsJson = 0x0100;
        public const int PasteAsTaml = 0x0110;
        public const int OpenSettings = 0x0200;
    }
}
